### ISSUE TITLE
(!) Move the mappings to gsheet

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/AAT-Term-Mappings#4]
@caknoblock @workergnome 
I strongly suggest to move these mappings from XSLX on github to google sheets. (Maybe a single sheet with many tabs, to allow easier comparison between museums.) Then we can all collaborate there, and I can add cols to post suggestions etc.

Posting separate issues for each concept is not efficient.

An open gsheet can be exposed as TSV or CSV by URL, so Karma can easily consume it.

**Comment by caknoblock** [comment]
Good idea, but just not possible in this phase due to limited resources.  We have it set up already so that the GitHub files can just be updated and it will automatically be incorporated into the mappings.
Craig

**Comment by VladimirAlexiev** [comment]
So what is the schedule of updates? Is it expected for any of the museums to update their XLSes, and based on what input? "Just" is made so much harder because you cant edit/comment XSLes on Github.

**Comment by caknoblock** [comment]
This information was collected by the data working group.  I have added Kate to the discussion since she lead this group.  I’m not sure what the plans are for updates here, but we can easily incorporate updates added to the AAT-Term-Mappings.

**Comment by kateblanch** [comment]
There are no plans for updating this data frequently. 
Would it make things easier if all 14 partner docs were compiled into 1 single .XLS on GitHub wtih the partner name in it's own column? I'm happy to move it into Google Docs, too - if that's helpful. 
Compiling the 14 docs into 1 document would make it easier to clone a working copy into Google docs.
I'm not sure how compiling into 1 document affects mappings. 
Please let me know your thoughts.

**Comment by caknoblock** [comment]
The code is configured now to work with the individual documents.  if we combine it into a single document, it will then need to be split up back into the individual files so that we don’t have to change the code.

**Comment by kateblanch** [comment]
OK, sounds like the right thing to do is just leave them as is.
@VladimirAlexiev - if it helps your review, I'd be happy to make a copy for you in GDocs, but obviously any changes would have to be mirrored to the source files here in GitHub.

**Comment by VladimirAlexiev** [comment]
Ok, let's leave them where they are
